# Generated by Django 5.2.11 on 2026-03-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Us  er Profile', 'verbose_name_plural': 'User ?Profiles'},
        ),
    ]
