# Generated by Django 5.2.11 on 2026-03-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('average_lifespan', models.CharField(blank=True, help_text='e.g., 10-15 years', max_length=50)),
                ('average_size', models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', max_length=20)),
                ('temperament', models.TextField(blank=True, help_text='General temperament traits')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'breeds',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon filename from static/images/icons/pet_category/', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pet Category',
                'verbose_name_plural': 'Pet Categories',
                'db_table': 'pet_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PetHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('checkup', 'Health Checkup'), ('surgery', 'Surgery'), ('treatment', 'Treatment'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('veterinarian_name', models.CharField(blank=True, max_length=200)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(blank=True, null=True, upload_to='health_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pet Health Record',
                'verbose_name_plural': 'Pet Health Records',
                'db_table': 'pet_health_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'db_table': 'pet_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('age_years', models.PositiveSmallIntegerField(default=0)),
                ('age_months', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_neutered', models.BooleanField(default=False)),
                ('health_certificate', models.FileField(blank=True, null=True, upload_to='health_certificates/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('adoption', 'For Adoption')], default='sale', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('adopted', 'Adopted')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.breed')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
