# Generated by Django 5.2.11 on 2026-03-02 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('reviews', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='pet_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.petreview'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order that verified this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='seller_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.sellerreview'),
        ),
        migrations.AlterUniqueTogether(
            name='petreview',
            unique_together={('pet', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('seller', 'reviewer')},
        ),
    ]
