# Generated by Django 5.2.11 on 2026-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('method', models.CharField(blank=True, help_text='Phone call, home visit, etc.', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('pet_condition', models.CharField(blank=True, help_text='How is the pet doing?', max_length=100)),
                ('concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adoption Follow-Up',
                'verbose_name_plural': 'Adoption Follow-Ups',
                'db_table': 'adoption_follow_ups',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('living_situation', models.CharField(choices=[('house_with_yard', 'House with Yard'), ('house_no_yard', 'House without Yard'), ('apartment', 'Apartment'), ('farm', 'Farm/Rural Property'), ('other', 'Other')], max_length=20)),
                ('living_situation_details', models.TextField(blank=True, help_text='Please describe your living situation')),
                ('has_other_pets', models.BooleanField(default=False)),
                ('other_pets_description', models.TextField(blank=True)),
                ('has_children', models.BooleanField(default=False)),
                ('children_ages', models.CharField(blank=True, help_text='Ages of children in household', max_length=100)),
                ('household_members', models.PositiveSmallIntegerField(default=1, help_text='Number of people in household')),
                ('experience_level', models.CharField(choices=[('first_time', 'First-time Pet Owner'), ('some', 'Some Experience'), ('experienced', 'Experienced Pet Owner'), ('professional', 'Professional/Breeder')], default='some', max_length=20)),
                ('experience_description', models.TextField(blank=True, help_text='Describe your experience with pets')),
                ('daily_hours_alone', models.PositiveSmallIntegerField(default=0, help_text='Hours pet will be alone daily')),
                ('veterinarian_name', models.CharField(blank=True, max_length=200)),
                ('veterinarian_phone', models.CharField(blank=True, max_length=20)),
                ('references', models.JSONField(blank=True, default=list)),
                ('agrees_to_home_visit', models.BooleanField(default=False)),
                ('agrees_to_followup', models.BooleanField(default=False)),
                ('agrees_to_return_policy', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal notes for review')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason shown to applicant if rejected')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adoption Request',
                'verbose_name_plural': 'Adoption Requests',
                'db_table': 'adoption_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
