# Generated by Django 5.2.11 on 2026-03-02 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('pets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionfollowup',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='adoptionfollowup',
            name='adoption_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='adoption.adoptionrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('pet', 'applicant')},
        ),
    ]
