# Generated by Django 5.2.11 on 2026-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Delivery'), ('mock_card', 'Credit/Debit Card (Legacy)'), ('mock_upi', 'UPI (Legacy)'), ('mock_netbanking', 'Net Banking (Legacy)'), ('mock_cod', 'Cash on Delivery (Legacy)')], max_length=20),
        ),
    ]
